Adjust the port

diff --git a/.github/workflows/lint-check-typescript.yml b/.github/workflows/lint-check-typescript.yml
--- a/.github/workflows/lint-check-typescript.yml
+++ b/.github/workflows/lint-check-typescript.yml
@@ -50,7 +50,19 @@ jobs:
       - name: Start DynamoDB Local
         uses: rrainn/dynamodb-action@v2.0.1
         with:
-          port: 8000
+          port: 8897
+
+      - name: Wait for DynamoDB
+        run: |
+          timeout=30
+          while ! nc -z localhost 8897; do
+            if [ $timeout -le 0 ]; then
+              echo "DynamoDB failed to start"
+              exit 1
+            fi
+            timeout=$((timeout-1))
+            sleep 1
+          done
 
       - name: Run Integration tests
         run: pnpm test:int
