Adding integration test to pipeline (#3)
* Adding integration test to pipeline

* Adjust the port

* Update and centralise duplicated configuration

* Use docker directly

* Updating the logic and ensuring the repository isolation is in place

* expose the query method

* Updating config based on the documentation

* Updating the test configuration

* Removing references to zod

* Adjusting config

* Fix vite error

diff --git a/.github/workflows/lint-check-typescript.yml b/.github/workflows/lint-check-typescript.yml
--- a/.github/workflows/lint-check-typescript.yml
+++ b/.github/workflows/lint-check-typescript.yml
@@ -44,6 +44,24 @@ jobs:
       - name: Check types
         run: pnpm check-types
 
-
-      - name: Run tests
+      - name: Run Unit tests
         run: pnpm test
+
+      - name: Start DynamoDB Local
+        run: |
+          docker compose up -d dynamodb
+
+      - name: Wait for DynamoDB
+        run: |
+          timeout=30
+          while ! nc -z localhost 8897; do
+            if [ $timeout -le 0 ]; then
+              echo "DynamoDB failed to start"
+              exit 1
+            fi
+            timeout=$((timeout-1))
+            sleep 1
+          done
+
+      - name: Run Integration tests
+        run: pnpm test:int
